package net.jitle.jitelcraft;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

public class JitelTabs {
    public static final DeferredRegister<CreativeModeTab> TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, JitelcraftMod.MODID);
    public static final RegistryObject<CreativeModeTab> JITELCRAFT_TAB = TABS.register("jitelcraft_tab",
            () -> CreativeModeTab.builder()
                    .icon(() -> new ItemStack(JitelItems.JITEL_GEM.get()))
                    .title(Component.translatable("itemGroup.jitelcraft.main"))
                    .displayItems((pParameters, pOutput) -> {
                        //MOD MATERIALS
                        pOutput.accept(JitelBlocks.JITEL_ORE.get());
                        pOutput.accept(JitelBlocks.JITEL_ORE_DEEPSLATE.get());
                        pOutput.accept(JitelItems.JITEL_GEM.get());
                        pOutput.accept(JitelItems.JITEL_NUGGET.get());
                        pOutput.accept(JitelBlocks.JITEL_BLOCK.get());
                        pOutput.accept(JitelItems.JITEL_DUST.get());
                        pOutput.accept(JitelBlocks.ZINC_ORE.get());
                        pOutput.accept(JitelBlocks.ZINC_ORE_DEEPSLATE.get());
                        pOutput.accept(JitelItems.ZINC_RAW.get());
                        pOutput.accept(JitelBlocks.ZINC_RAW_BLOCK.get());
                        pOutput.accept(JitelItems.ZINC_INGOT.get());
                        pOutput.accept(JitelItems.ZINC_NUGGET.get());
                        pOutput.accept(JitelBlocks.ZINC_BLOCK.get());
                        pOutput.accept(JitelItems.ZINC_ROD.get());
                        pOutput.accept(JitelItems.ZINC_PLATE.get());
                        pOutput.accept(JitelItems.ZINC_GEAR.get());
                        pOutput.accept(JitelItems.ZINC_DUST.get());
                        pOutput.accept(JitelBlocks.ALUMINUM_ORE.get());
                        pOutput.accept(JitelBlocks.ALUMINUM_ORE_DEEPSLATE.get());
                        pOutput.accept(JitelItems.ALUMINUM_RAW.get());
                        pOutput.accept(JitelBlocks.ALUMINUM_RAW_BLOCK.get());
                        pOutput.accept(JitelItems.ALUMINUM_INGOT.get());
                        pOutput.accept(JitelItems.ALUMINUM_NUGGET.get());
                        pOutput.accept(JitelBlocks.ALUMINUM_BLOCK.get());
                        pOutput.accept(JitelItems.ALUMINUM_ROD.get());
                        pOutput.accept(JitelItems.ALUMINUM_PLATE.get());
                        pOutput.accept(JitelItems.ALUMINUM_GEAR.get());
                        pOutput.accept(JitelItems.ALUMINUM_DUST.get());
                        pOutput.accept(JitelItems.ALUMINUM_WIRE.get());
                        pOutput.accept(JitelItems.STEEL_COMPONENTS.get());
                        pOutput.accept(JitelItems.STEEL_INGOT.get());
                        pOutput.accept(JitelItems.STEEL_NUGGET.get());
                        pOutput.accept(JitelBlocks.STEEL_BLOCK.get());
                        pOutput.accept(JitelItems.STEEL_ROD.get());
                        pOutput.accept(JitelItems.STEEL_PLATE.get());
                        pOutput.accept(JitelItems.STEEL_GEAR.get());
                        pOutput.accept(JitelItems.STEEL_DUST.get());
                        pOutput.accept(JitelItems.BRASS_COMPONENTS.get());
                        pOutput.accept(JitelItems.BRASS_INGOT.get());
                        pOutput.accept(JitelItems.BRASS_NUGGET.get());
                        pOutput.accept(JitelBlocks.BRASS_BLOCK.get());
                        pOutput.accept(JitelItems.BRASS_ROD.get());
                        pOutput.accept(JitelItems.BRASS_PLATE.get());
                        pOutput.accept(JitelItems.BRASS_GEAR.get());
                        pOutput.accept(JitelItems.BRASS_DUST.get());
                        pOutput.accept(JitelBlocks.OPAL_ORE.get());
                        pOutput.accept(JitelBlocks.OPAL_ORE_DEEPSLATE.get());
                        pOutput.accept(JitelItems.OPAL_GEM.get());
                        pOutput.accept(JitelItems.OPAL_NUGGET.get());
                        pOutput.accept(JitelBlocks.OPAL_BLOCK.get());
                        pOutput.accept(JitelItems.OPAL_ROD.get());
                        pOutput.accept(JitelItems.OPAL_PLATE.get());
                        pOutput.accept(JitelItems.OPAL_GEAR.get());
                        pOutput.accept(JitelItems.OPAL_DUST.get());
                        pOutput.accept(JitelBlocks.HALITE.get());
                        pOutput.accept(JitelItems.SALT.get());
                        //VANILLA MATERIALS
                        pOutput.accept(JitelItems.WOODEN_GEAR.get());
                        pOutput.accept(JitelItems.STICK_INGOT.get());
                        pOutput.accept(JitelItems.STONE_ROD.get());
                        pOutput.accept(JitelItems.COAL_PLATE.get());
                        pOutput.accept(JitelItems.COAL_DUST.get());
                        pOutput.accept(JitelItems.COPPER_NUGGET.get());
                        pOutput.accept(JitelItems.COPPER_ROD.get());
                        pOutput.accept(JitelItems.COPPER_PLATE.get());
                        pOutput.accept(JitelItems.COPPER_GEAR.get());
                        pOutput.accept(JitelItems.COPPER_DUST.get());
                        pOutput.accept(JitelItems.COPPER_WIRE.get());
                        pOutput.accept(JitelItems.IRON_ROD.get());
                        pOutput.accept(JitelItems.IRON_PLATE.get());
                        pOutput.accept(JitelItems.IRON_GEAR.get());
                        pOutput.accept(JitelItems.IRON_DUST.get());
                        pOutput.accept(JitelItems.GOLD_ROD.get());
                        pOutput.accept(JitelItems.GOLD_PLATE.get());
                        pOutput.accept(JitelItems.GOLD_GEAR.get());
                        pOutput.accept(JitelItems.GOLD_DUST.get());
                        pOutput.accept(JitelItems.DIAMOND_NUGGET.get());
                        pOutput.accept(JitelItems.DIAMOND_ROD.get());
                        pOutput.accept(JitelItems.DIAMOND_PLATE.get());
                        pOutput.accept(JitelItems.DIAMOND_GEAR.get());
                        pOutput.accept(JitelItems.DIAMOND_DUST.get());
                        pOutput.accept(JitelItems.EMERALD_NUGGET.get());
                        pOutput.accept(JitelItems.EMERALD_ROD.get());
                        pOutput.accept(JitelItems.EMERALD_PLATE.get());
                        pOutput.accept(JitelItems.EMERALD_GEAR.get());
                        pOutput.accept(JitelItems.EMERALD_DUST.get());
                        pOutput.accept(JitelItems.NETHERITE_NUGGET.get());
                        pOutput.accept(JitelItems.NETHERITE_ROD.get());
                        pOutput.accept(JitelItems.NETHERITE_PLATE.get());
                        pOutput.accept(JitelItems.NETHERITE_GEAR.get());
                        pOutput.accept(JitelItems.NETHERITE_DUST.get());
                        pOutput.accept(JitelItems.LAPIS_NUGGET.get());
                        pOutput.accept(JitelItems.LAPIS_ROD.get());
                        pOutput.accept(JitelItems.LAPIS_PLATE.get());
                        pOutput.accept(JitelItems.LAPIS_GEAR.get());
                        pOutput.accept(JitelItems.LAPIS_DUST.get());
                        pOutput.accept(JitelItems.QUARTZ_NUGGET.get());
                        pOutput.accept(JitelItems.QUARTZ_ROD.get());
                        pOutput.accept(JitelItems.QUARTZ_PLATE.get());
                        pOutput.accept(JitelItems.QUARTZ_GEAR.get());
                        pOutput.accept(JitelItems.QUARTZ_DUST.get());
                        pOutput.accept(JitelItems.AMETHYST_NUGGET.get());
                        pOutput.accept(JitelItems.AMETHYST_ROD.get());
                        pOutput.accept(JitelItems.AMETHYST_PLATE.get());
                        pOutput.accept(JitelItems.AMETHYST_GEAR.get());
                        pOutput.accept(JitelItems.AMETHYST_DUST.get());
                        //TIER 1
                        pOutput.accept(JitelItems.MOTOR_TIER1.get());
                        pOutput.accept(JitelItems.CONTROLLER_TIER1.get());
                        pOutput.accept(JitelItems.MOTOR_TIER1_DOWN.get());
                        pOutput.accept(JitelItems.CONTROLLER_TIER1_DOWN.get());
                        pOutput.accept(JitelBlocks.CASING_WOODEN.get());
                        pOutput.accept(JitelBlocks.CRUSHER_TIER1.get());
                        //TIER 2
                        pOutput.accept(JitelItems.MOTOR_TIER2.get());
                        pOutput.accept(JitelItems.CONTROLLER_TIER2.get());
                        pOutput.accept(JitelItems.MOTOR_TIER2_DOWN.get());
                        pOutput.accept(JitelItems.CONTROLLER_TIER2_DOWN.get());
                        pOutput.accept(JitelBlocks.CASING_STONE.get());
                        pOutput.accept(JitelBlocks.CRUSHER_TIER2.get());
                        //OTHER
                        pOutput.accept(JitelItems.CRUSHER_PART.get());
                        pOutput.accept(JitelItems.COIL.get());
                        pOutput.accept(JitelItems.COIL_COPPER.get());
                        pOutput.accept(JitelItems.COIL_ALUMINUM.get());
                        pOutput.accept(JitelItems.HAMMER.get());
                        pOutput.accept(JitelItems.JITEL_SWORD.get());
                        pOutput.accept(JitelItems.CURSED_PICKAXE.get());
                        pOutput.accept(JitelItems.PLATE_HELMET.get());
                        pOutput.accept(JitelItems.PLATE_CHESTPLATE.get());
                        //BLOCKS
                        pOutput.accept(JitelBlocks.IRON_DOOR_WL.get());
                        pOutput.accept(JitelBlocks.IRON_TRAPDOOR_WL.get());
                        pOutput.accept(JitelBlocks.OMNIHOPPER.get());
                        pOutput.accept(JitelBlocks.LUXMETER.get());
                        pOutput.accept(JitelBlocks.LAMP_ANALOG.get());
                        pOutput.accept(JitelBlocks.COILBLOCK_COPPER.get());
                        pOutput.accept(JitelBlocks.COILBLOCK_ALUMINUM.get());
                        pOutput.accept(JitelBlocks.POINTER_BLOCK.get());
                        pOutput.accept(JitelBlocks.POINTER_PILLAR.get());
                        pOutput.accept(JitelBlocks.CHROMAKEY_WHITE.get());
                        pOutput.accept(JitelBlocks.CHROMAKEY_LIGHT_GRAY.get());
                        pOutput.accept(JitelBlocks.CHROMAKEY_GRAY.get());
                        pOutput.accept(JitelBlocks.CHROMAKEY_BLACK.get());
                        pOutput.accept(JitelBlocks.CHROMAKEY_BROWN.get());
                        pOutput.accept(JitelBlocks.CHROMAKEY_RED.get());
                        pOutput.accept(JitelBlocks.CHROMAKEY_ORANGE.get());
                        pOutput.accept(JitelBlocks.CHROMAKEY_YELLOW.get());
                        pOutput.accept(JitelBlocks.CHROMAKEY_LIME.get());
                        pOutput.accept(JitelBlocks.CHROMAKEY_GREEN.get());
                        pOutput.accept(JitelBlocks.CHROMAKEY_CYAN.get());
                        pOutput.accept(JitelBlocks.CHROMAKEY_LIGHT_BLUE.get());
                        pOutput.accept(JitelBlocks.CHROMAKEY_BLUE.get());
                        pOutput.accept(JitelBlocks.CHROMAKEY_PURPLE.get());
                        pOutput.accept(JitelBlocks.CHROMAKEY_MAGENTA.get());
                        pOutput.accept(JitelBlocks.CHROMAKEY_PINK.get());
                        pOutput.accept(JitelBlocks.NO_TEXTURE_BLOCK.get());
                        pOutput.accept(JitelBlocks.NO_TEXTURE_STAIRS.get());
                        pOutput.accept(JitelBlocks.NO_TEXTURE_SLAB.get());
                        pOutput.accept(JitelBlocks.NO_TEXTURE_WALL.get());
                        pOutput.accept(JitelBlocks.NO_TEXTURE_BRICKS.get());
                        pOutput.accept(JitelBlocks.NO_TEXTURE_BRICKS_STAIRS.get());
                        pOutput.accept(JitelBlocks.NO_TEXTURE_BRICKS_SLAB.get());
                        pOutput.accept(JitelBlocks.NO_TEXTURE_BRICKS_WALL.get());
                    })
                    .build()
    );
}